### ISSUE TITLE
模拟知乎登录的时候出现证书错误

### ISSUE THREAD

**Issue by yueruchen** [xchaoinfo/fuck-login#74]
Cookie 未能加载
Traceback (most recent call last):
  File "zhihu.py", line 135, in <module>
    if isLogin():
  File "zhihu.py", line 82, in isLogin
    login_code = session.get(url, headers=headers, allow_redirects=False).status_code
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

把 82行   login_code = session.get(url, headers=headers, allow_redirects=False).status_code
改为
 login_code = session.get(url, headers=headers, allow_redirects=False，verify=False).status_code

**Comment by yueruchen** [comment]
环境：Ubuntu 14.04.4
